---

- name: Install Apache2 and php etc
  apt: name={{ item }} state=present update_cache=true
  with_items:
   - apache2
   - php5
   - libapache2-mod-php5
   - php5-mcrypt

- name: Httpd service state
  service: name=apache2 state=started enabled=yes
