---

- name: Install Apache2 and php etc
  yum: name={{ item }} state=present update_cache=true
  with_items:
   - httpd
   - php5
   - libapache2-mod-php5
   - php5-mcrypt

- name: Httpd service state
  service: name=httpd state=started enabled=yes
