---

- name: install mysql
  apt: pkg=mysql-server state=latest
       update_cache=yes cache_valid_time=86400
  sudo: yes

- name: Create database
  mysql_db: name={{ mysqlDatabase }}
            state=present
  sudo: yes

- name: Create database user
  mysql_user: name={{ mysqlUser }} password={{ mysqlPasswd }} priv={{ mysqlDatabase }}.*:ALL,GRANT state=present
  sudo: yes

- name: Installing Debian Git
  apt: pkg=git state=latest
       update_cache=yes cache_valid_time=86400
  sudo: yes

- name: Download Stash installer into /tmp
  get_url: url={{ stashUrl }}
           dest=/tmp
  sudo: yes

- name: Set Perms on Stash File
  file: path=/tmp/{{ stashExec }}
        owner=root
        group=root
        mode=0777
  sudo: yes

- name: Copy Stash Template
  template: src=response.varfile.j2
            dest=/tmp/response.varfile
  sudo: yes

- name: Install Stash
  raw: /tmp/{{ stashExec }} -q -varfile /tmp/response.varfile
  sudo: yes

- name: Create Stash Lib
  file: path={{ stashHome }}/lib
        owner=atlstash
        group=atlstash
        state=directory
  sudo: yes

- name: Copy Stash init.d File
  template: src=stash.init.d.j2
            dest=/etc/init.d/stash
  sudo: yes

#- name: Download MySQL Connector
#  get_url: url={{ mysqlConnectorUrl }}
#           dest=/tmp
#  sudo: yes

#- name: Unarchive MySQL Connector
#  unarchive: src=/tmp/{{ mysqlConnectorTar }}
#             dest=/tmp/{{ mysqlConnectorDir }}
#             copy=no
#  sudo: yes

- name: Move MySQL Connector to Stash
  copy: src={{ mysqlConnectorJar }}
        dest={{ stashData }}/lib/{{ mysqlConnectorJar }}
        owner=atlstash
        group=atlstash
        mode=0644
  sudo: yes

- name: stop stash
  service: name=atlstash
           state=stopped
  sudo: yes

- name: start stash
  service: name=atlstash
           state=started
  sudo: yes
