---

- name: Add PostgreSQL Repository to yum.conf.d
  template: src=pgsql.repo.j2
            dest=/etc/yum.repos.d/pgsql.repo
            user=root
            group=root
            mode=0644
            state=present

- name: Install PostgreSQL Packages
  sudo: yes
  yum: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - {{ pgsql.items }}

- name: Create Postgres databases
  sudo: yes
  sudo_user: {{ pgsql.admin }}
  postgresql_db: name={{ pgsql.database }}
                 state=present

- name: Create Postgres users
  sudo: yes
  sudo_user: {{ pgsql.admin }}
  postgresql_user: name={{ pgsql.user }}
                   password={{ pgsql.password }}
                   db={{ pgsql.database }}
                   priv=ALL

- name: Set Authentication config
  sudo: yes
  template: src={{ pgsql.auth_template }}
            dest="/etc/postgresql/{{ version_number }}/main/pg_hba.conf"
  notify: Restart postgres

- name: Restart postgres immediately
  service: name=postgresql enabled=yes state=restarted
